### ISSUE TITLE
Default items.csv contains exploitable single vs stack prices

### ISSUE THREAD

**Issue by towbes** [AdamGagorik/ffxiahbot#43]
There are multiple instances in the default items.csv where buying a stack of an item and reselling as singles results in gil printing.

As a quick fix for the base file, I modified the price01 column to be floor(price12 / 12).  If the stack price was 1, the price01 column remained unchange.  This gives server admins a peace of mind that they can tune prices without having easily exploitable price conditions on the AH out of the box.  (There is still a risk of things being sold under NPC price).  

[items-NoStackExploits.csv](https://github.com/AdamGagorik/pydarkstar/files/8665328/items-NoStackExploits.csv)

Edit: How can I export the CSV from google sheets with that nice tabs to make columns in a text editor?

**Comment by TeoTwawki** [comment]
> Edit: How can I export the CSV from google sheets with that nice tabs to make columns in a text editor?

I've used textFx plugin in notepad++ to align by comma, then shift the whitespace to the correct side of the comma/word

**Comment by AdamGagorik** [comment]
The idea behind the `items.csv` was that you edit it up however you want.  Creating one from `ffxiah.com` was just meant to be starting point.

I don't know what the hell I was thinking with the fixed width layout of the CSV.  I wrote all kinds of unnecessary custom parsing logic because I did not know better at the time.

I would like to make the CSV simpler and load it with pandas.

**Comment by AdamGagorik** [comment]
If you want you can make a PR to update the default `items.csv` with prices that are not exploitable.  For now I will close this issue.
