### ISSUE TITLE
Errors with regex, itemlist.py

### ISSUE THREAD

**Issue by lordlarr** [AdamGagorik/ffxiahbot#44]
Hello, I'm not really a coder, but I do my best and I think I'm having an issue with regex when trying to get the AH to populate.
my best attempts to understand, points me to believe that its a difference in how re works across different versions of python? As I said, Im not a coder at all so I have no real clue. lol Any help would be appreciated! Thank you!

 File "D:\server\ahbot\pydarkstar\pydarkstar\apps\refill\run.py", line 32, in main
    idata = ItemList.from_csv(*opts.data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\server\ahbot\pydarkstar\pydarkstar\itemlist.py", line 30, in from_csv
    obj.loadcsv(f)
  File "D:\server\ahbot\pydarkstar\pydarkstar\itemlist.py", line 94, in loadcsv
    line = regex_c.sub('', line).strip()
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object

**Comment by AdamGagorik** [comment]
@lordlarr 

I can tell by how the error is formatted that this message is from Python 3.11 - I think that the codebase is not compatible with this version of Python.  I think you could uninstall Python 3.11 and try a slightly older version, such as Python 3.7 instead.  I know the README said otherwise, but I guess no one saw the 3.11 incompatibility until now.

**Comment by AdamGagorik** [comment]
The codebase has been migrated to Python 3.12, so I think this issue is no longer relevant.
