### ISSUE TITLE
Issue with uv run ffxiahbot --verbose scrub --server ASURA

### ISSUE THREAD

**Issue by YummySushi13** [AdamGagorik/ffxiahbot#62]
Running the cmd loads everything up and it shows that it is gathering data. 

about 10 minutes later it throws this error, and does not create a new csv file with the updated prices from the AH. 

![image](https://github.com/user-attachments/assets/82b8c056-3c0f-4195-8494-836e6be6ac04)

Does anyone have any idea on how to fix this error?

**Comment by AdamGagorik** [comment]
Any chance there is some additional info a little further up in the terminal?  This is suggesting to me that the item ID fetched from ffxiah is invalid.

**Comment by AdamGagorik** [comment]
For example, it might debug the URL being parsed right before the error.
In the mean time, I will run it on my side to see if I can reproduce this.

**Comment by YummySushi13** [comment]
I’ll run it again tonight and report the full report

**Comment by AdamGagorik** [comment]
I think I found the issue and fixed it in the latest update.

- No price was found on ffxiah
- Therefore the price was set to None
- pydantic complained that price was not an int

I fixed this by setting the price to zero instead of None, ensuring elsewhere that 0 priced items are neither bought nor sold by the broker.

**Comment by AdamGagorik** [comment]
Writing to confirm I was able to reproduce this issue.  After the fix I can run it to completion.

**Comment by YummySushi13** [comment]
So i just need to download the newest version and it will work?
